#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: O Telégrafo --. -. -..

# Name of the author
author: Danny Tonidandel

# Short bio or description (displayed in the header)
description: Um blog de pesquisa sobre História e Filosofia da Ciência.

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /images/fig09.png

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  researchgate: Danny_Tonidandel # includes the RG footer-link
  dribbble:
  email: danny@otelegrafo.com
  facebook:
  flickr:
  github: tonidandel
  instagram: otelegrafo_
  orcid: 0000-0003-3845-6479
  linkedin:
  pinterest:
  rss: rss
  twitter:
  stackoverflow:
  youtube: channel/UCqKlUW7ebELab5cC8olp1pQ
  googleplus: # anything in your profile username that comes after plus.google.com/
  playconsole:
  lattes: 7661349034478084

# Timezone
  timezone: America/Sao_Paulo
# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
  disqus: otelegrafo
  comments: true

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-154668176-1

# Your website URL
# Used for Sitemap.xml and your RSS feed
url: https://otelegrafo.com
enforce_ssl: otelegrafo.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#baseurl: "/blog2"

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-seo-tag
  - jekyll-paginate

include: ['_pages']

paginate: 6
paginate_path: /page:num/

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
